[project]
name = "rag-scientific-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "datasets>=4.5.0",
    "lxml>=6.0.2",
    "tensorflow>=2.20.0",
    "tensorflow-datasets>=4.9.9",
]
